# Generated by Django 4.1.7 on 2023-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ram_storage_remove_product_variant_variation_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
