# Generated by Django 4.1.7 on 2023-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
