# Generated by Django 4.1.7 on 2023-03-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_coupon_discount_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
