# Generated by Django 4.1.7 on 2023-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_picture/propic.png', null=True, upload_to='profile_picture'),
        ),
    ]
