# Generated by Django 4.1.7 on 2023-03-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_razorpay_order_id_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
    ]
