# Generated by Django 4.1.7 on 2023-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
