# Generated by Django 4.1.7 on 2023-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
