# Generated by Django 4.1.7 on 2023-03-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='subject',
            new_name='title',
        ),
    ]
