# Generated by Django 4.1.7 on 2023-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_subject_reviewrating_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
