# Generated by Django 4.1.7 on 2023-03-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='title',
        ),
    ]
