# Generated by Django 4.1.7 on 2023-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('text_one', models.CharField(max_length=20)),
                ('text_two', models.CharField(max_length=20)),
            ],
        ),
    ]
